export const DATA = [
  {
    isOnline: true,
    isVerify: true,
    name: 'Bitservice',
    icon: null,
    rating: 4,
    country: 'Россия',
    method: 'Сбербанк (Российский рубль)',
    size: 0.02060073,
    limit: {
      min: 10000,
      max: 13789,
    },
    course: 677011.82,
    currency: 'RUB',
  },
  {
    isOnline: true,
    isVerify: true,
    name: 'Bitservice',
    icon: null,
    rating: 4,
    country: 'Россия',
    method: 'Сбербанк (Российский рубль)',
    size: 0.02060073,
    limit: {
      min: 10000,
      max: 13789,
    },
    course: 677011.82,
    currency: 'RUB',
  },
  {
    isOnline: true,
    isVerify: true,
    name: 'Bitservice',
    icon: null,
    rating: 4,
    country: 'Россия',
    method: 'Сбербанк (Российский рубль)',
    size: 0.02060073,
    limit: {
      min: 10000,
      max: 13789,
    },
    course: 677011.82,
    currency: 'RUB',
  },
];
